# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sinatra-default-templates}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Julio Cesar"]
  s.date = %q{2010-02-09}
  s.description = %q{Saves you from having to write routes just to render templates with the same name. Rails-style.}
  s.email = %q{julio.ody@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    "Readme.txt",
     "VERSION",
     "lib/sinatra/default_templates.rb",
     "spec/default_templates_spec.rb",
     "spec/dummy.rb",
     "spec/views/test.haml"
  ]
  s.homepage = %q{http://github.com/juliocesar/sinatra-default-templates}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Render a template in the absence of a route if one exists}
  s.test_files = [
    "spec/default_templates_spec.rb",
     "spec/dummy.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 1.0.a"])
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_development_dependency(%q<rack-test>, [">= 0.5.3"])
      s.add_development_dependency(%q<haml>, ["= 2.2.17"])
    else
      s.add_dependency(%q<sinatra>, [">= 1.0.a"])
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_dependency(%q<rack-test>, [">= 0.5.3"])
      s.add_dependency(%q<haml>, ["= 2.2.17"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 1.0.a"])
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
    s.add_dependency(%q<rack-test>, [">= 0.5.3"])
    s.add_dependency(%q<haml>, ["= 2.2.17"])
  end
end

